const en = {
  title: 'Remove background（Preview）',
  hint: 'Keep the subject and remove its background. Review the transparent result before applying.',
  original: 'Original',
  result: 'Result',
  retry: 'Retry',
  ready: 'Ready to apply',
  applying: 'Applying…',
  failed: 'Background removal failed.',
  stages: {
    connecting: 'Connecting to Image Lab…',
    queued: 'Waiting to process…',
    running: 'Processing…',
    preparing_image: 'Preparing image…',
    loading_model: 'Preparing model; first use may take longer…',
    preprocessing: 'Preparing image…',
    identifying_subject: 'Identifying the subject…',
    generating_mask: 'Separating the background…',
    cleaning_edges: 'Refining edges…',
    compositing: 'Compositing transparent image…',
    encoding_result: 'Preparing result…',
    downloading: 'Loading result…',
  } as Record<string, string>,
}
const zh: typeof en = {
  title: '去除背景（Preview）',
  hint: '保留主体、移除背景，确认透明效果后再应用到图片。',
  original: '原图',
  result: '处理结果',
  retry: '重试',
  ready: '处理完成，可以应用',
  applying: '正在应用…',
  failed: '去除背景失败。',
  stages: {
    connecting: '正在连接 Image Lab…',
    queued: '正在等待处理…',
    running: '正在处理…',
    preparing_image: '正在准备图片…',
    loading_model: '正在准备模型，首次使用可能需要稍等…',
    preprocessing: '正在准备图片…',
    identifying_subject: '正在识别主体…',
    generating_mask: '正在分离背景…',
    cleaning_edges: '正在优化边缘…',
    compositing: '正在合成透明图片…',
    encoding_result: '正在准备结果…',
    downloading: '正在加载结果…',
  },
}
export const imageLabStrings = (lang: string): typeof en => (lang.startsWith('zh') ? zh : en)
