const en = {
  imageTools: 'Image tools',
  addRegion: 'Add region',
  editRegion: 'Adjust region',
  cancelCrop: 'Cancel adjustment',
  hideRegions: 'Hide regions',
  showRegions: 'Show regions',
  zoom: 'Image zoom',
  pickRegion: 'Choose a numbered region to compare its fonts, or add your own selection.',
  manualRegion: 'Manual region',
  reviewRegion: 'Needs review',
  failedRegion: 'Recognition failed',
  scoreHint: 'Ranking score, not recognition accuracy.',
  cropArea: 'Text region; use arrow keys to move',
  nwHandle: 'Resize top-left corner',
  nHandle: 'Resize top edge',
  neHandle: 'Resize top-right corner',
  eHandle: 'Resize right edge',
  seHandle: 'Resize bottom-right corner',
  sHandle: 'Resize bottom edge',
  swHandle: 'Resize bottom-left corner',
  wHandle: 'Resize left edge',

  preparingFont: 'Preparing font download…',
  downloadingFont: 'Downloading font…',
  verifyingFont: 'Checking font file…',
  loadingFont: 'Loading font…',
  installingFont: 'Adding and loading font…',
  savingFont: 'Downloading / saving font…',
  applyingFont: 'Adding and applying font…',
  fontReady: 'Font is ready to use.',
  fontLoadFailed: 'Font loading failed. Please try again.',
  fontDownloadFailed: 'Font download failed. Please try again.',
  retry: 'Retry',
  downloadOnly: 'This font can be downloaded. Adding requires a static TTF or OTF variant.',
  title: 'Find font from image（Preview）',
  entry: 'Find font from image（Preview）…',
  pictureEntry: 'Identify image font（Preview）…',
  subtitle: 'Select text in a reference image, then preview and choose a similar font.',
  reference: 'Reference image',
  upload: 'Upload image',
  paste: 'Paste image',
  document: 'Pick from document',
  empty: 'Upload or paste a PNG, JPEG or WebP image (up to 10 MB).',
  crop: 'Select text, then drag edges or use arrow keys to adjust. Minimum 8 × 8 pixels.',
  scan: 'Identify font',
  scanning: 'Identifying…',
  loading: 'Loading…',
  candidates: 'Font candidates',
  noResults: 'No font candidates found. Select a clearer text region and try again.',
  beforeScan: 'Choose an image and identify its fonts.',
  similar: 'Closest match',
  variant: 'Weight / style',
  preview: 'Preview text',
  suggestion: 'Suggestions are similar fonts, not guaranteed matches.',
  download: 'Download font',
  add: 'Add to GenOffice',
  apply: 'Add and apply',
  added: 'Font added to GenOffice.',
  downloaded: 'Font downloaded.',
  sourceOnly: 'Identify and add fonts; no editable text is selected.',
  target: 'Apply to',
  close: 'Close',
  noClipboard: 'No supported image on the clipboard. Try pasting with Ctrl/⌘+V.',
  unsupported: 'Choose a PNG, JPEG or WebP image smaller than 10 MB.',
  smallCrop: 'Select a region at least 8 × 8 pixels.',
  previewError: 'This font cannot be previewed in this editor.',
  noImages: 'No pictures in this presentation.',
  back: 'Back',
  regions: 'Text regions',
}
const zh: typeof en = {
  imageTools: '图片工具',
  addRegion: '添加选区',
  editRegion: '调整选区',
  cancelCrop: '取消调整',
  hideRegions: '隐藏区域标注',
  showRegions: '显示区域标注',
  zoom: '图片缩放',
  pickRegion: '点击编号选区比较字体，也可以手动添加选区。',
  manualRegion: '手动选区',
  reviewRegion: '待确认',
  failedRegion: '识别失败',
  scoreHint: '模型评分用于候选排序，不代表识别准确率。',
  cropArea: '文字识别选区，可用方向键移动',
  nwHandle: '调整选区左上角',
  nHandle: '调整选区上边缘',
  neHandle: '调整选区右上角',
  eHandle: '调整选区右边缘',
  seHandle: '调整选区右下角',
  sHandle: '调整选区下边缘',
  swHandle: '调整选区左下角',
  wHandle: '调整选区左边缘',

  preparingFont: '正在准备字体下载…',
  downloadingFont: '正在下载字体…',
  verifyingFont: '正在校验字体文件…',
  loadingFont: '正在加载字体…',
  installingFont: '正在添加并加载字体…',
  savingFont: '正在下载／保存字体…',
  applyingFont: '正在添加并应用字体…',
  fontReady: '字体已就绪，可以使用。',
  fontLoadFailed: '字体加载失败，请重试。',
  fontDownloadFailed: '字体下载失败，请重试。',
  retry: '重试',
  downloadOnly: '此字体可下载；添加到 GenOffice 需要选择静态 TTF 或 OTF 字体。',
  title: '从图片找字体（Preview）',
  entry: '从图片找字体（Preview）…',
  pictureEntry: '识别图片字体（Preview）…',
  subtitle: '框选参考图片中的文字，预览并选择相似字体。',
  reference: '参考图片',
  upload: '上传图片',
  paste: '粘贴图片',
  document: '从文档选取图片',
  empty: '上传或粘贴 PNG、JPEG 或 WebP 图片（最大 10 MB）。',
  crop: '框住同一种字体；拖动边角或用方向键微调，至少 8 × 8 像素。',
  scan: '识别字体',
  scanning: '正在识别…',
  loading: '正在加载…',
  candidates: '候选字体',
  noResults: '未找到候选字体，请框选更清晰的文字区域重试。',
  beforeScan: '选择图片后，识别其中的字体。',
  similar: '最相似',
  variant: '字重／样式',
  preview: '预览文字',
  suggestion: '结果为相似字体建议，不保证与原图完全一致。',
  download: '下载字体',
  add: '添加到 GenOffice',
  apply: '添加并应用',
  added: '字体已添加到 GenOffice。',
  downloaded: '字体已下载。',
  sourceOnly: '当前未选择可编辑文字，可识别、下载和添加字体。',
  target: '应用到',
  close: '关闭',
  noClipboard: '剪贴板中没有支持的图片，也可以按 Ctrl/⌘+V 粘贴。',
  unsupported: '请选择小于 10 MB 的 PNG、JPEG 或 WebP 图片。',
  smallCrop: '请框选至少 8 × 8 像素的区域。',
  previewError: '该字体无法在此编辑器中预览。',
  noImages: '当前演示文稿中没有图片。',
  back: '返回',
  regions: '文字区域',
}
export function fontPickerStrings(lang: string): typeof en {
  return lang.startsWith('zh') ? zh : en
}
